title: "Sakaguchi Daimon"
description: "Personal academic homepage for Sakaguchi Daimon."
url: "https://saka-d.github.io"
baseurl: "/homepage"

theme: null
plugins: []

exclude:
  - .gitignore
  - package.json
  - README.md
  - node_modules
