title: "坂口 大門 | Daimon Sakaguchi"
description: "坂口 大門（Daimon Sakaguchi）の個人・学術ホームページ。"
url: "https://saka-d.github.io"
baseurl: "/homepage"

theme: null
plugins: []

exclude:
  - .gitignore
  - package.json
  - README.md
  - node_modules
