export const academicPages = [
  {
    file: "pages/cv.html", active: "cv", title: "CV | Daimon Sakaguchi",
    description: "Curriculum vitae of Daimon Sakaguchi: affiliation, research visits, awards, fellowships, and research support.",
    body: `<section class="page-hero"><div class="container"><p class="eyebrow">Curriculum Vitae</p><h1>CV</h1><p class="lead">Affiliation, research visits, research theme, awards, fellowships, and research support.</p></div></section><section class="section-band"><div class="container content-grid"><aside class="side-summary"><h2>Daimon Sakaguchi</h2><p>Department of Chemistry and Life Science, Graduate School of Engineering Science, Yokohama National University<br>Physical Organic Chemistry and Molecular Design Laboratory (Gotoh Laboratory)</p><a class="btn btn-secondary" href="publications.html">Publications</a></aside><div class="content-stack">
      <article><h2>Affiliation</h2><ol class="timeline-list compact"><li><time>Current</time><span>Department of Chemistry and Life Science, Graduate School of Engineering Science, Yokohama National University</span></li></ol></article>
      <article><h2>Education and Research Visits</h2><ol class="timeline-list compact"><li><time>2026.09–10 (forthcoming)</time><span><a href="https://researchmap.jp/sakaguchi-daimon/education/54196884" target="_blank" rel="noopener noreferrer">Department of Chemistry, Faculty of Science, The University of British Columbia (J. P. Reid Laboratory)</a></span></li><li><time>2025.09–10</time><span><a href="https://researchmap.jp/sakaguchi-daimon/education/53900766" target="_blank" rel="noopener noreferrer">Quantum Chemistry Laboratory, Graduate School of Chemical Sciences and Engineering, Hokkaido University (MANABIYA Joint Research Program)</a></span></li></ol></article>
      <article><h2>Research Theme</h2><ol class="timeline-list compact"><li><time>Theme</time><span>Elucidating the origins of reaction selectivity using stereoelectronic-state informatics</span></li></ol></article>
      <article><h2>Awards and Honors</h2><ol class="timeline-list compact"><li><time>2026.06</time><span>Outstanding Poster Award, 2026 Spring Meeting of the Society of Computer Chemistry, Japan.<br>Presentation: Prediction and interpretation of reaction selectivity through data-driven analysis of noncovalent-interaction fields in transition states. <a href="https://www.sccj.net/aboutus/award/" target="_blank" rel="noopener noreferrer">SCCJ</a></span></li><li><time>2024.12</time><span>Outstanding Presentation Award, 47th Chemoinformatics Discussion Meeting.<br>Presentation: Prediction and interpretation of enantioselectivity in asymmetric ketone reduction using a molecular-field analysis method that evaluates electronic states. <a href="https://sites.google.com/view/chemoinfo2024/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0" target="_blank" rel="noopener noreferrer">Program</a></span></li></ol></article>
      <article><h2>Research Support</h2><ul class="detail-list"><li><strong>JSPS Research Fellowship for Young Scientists (DC2)</strong><span>Selected for FY2026. Project: “Quantitative elucidation of the relationship between stereoelectronic states and reaction facial selectivity using data-driven methods.” <a href="https://www.jsps.go.jp/file/storage/j-pd/data/list_of_recruits/R8_DC2_Saiyou.pdf" target="_blank" rel="noopener noreferrer">JSPS</a></span></li><li><strong>SPReAD: Exploratory Research for AI for Science</strong><span>Selected in the first FY2026 call. Principal investigator for “Development of reaction-selectivity prediction AI by integrating reaction-path exploration and stereoelectronic-state analysis.” <a href="https://www.mext.go.jp/content/20260629-mxt_jyohoka01-000050750_5.pdf" target="_blank" rel="noopener noreferrer">MEXT</a></span></li><li><strong>YNU-BOOST</strong><span>Next-generation AI researcher-development project addressing social challenges through co-creation among diverse AI approaches. <a href="https://ai.ynu.ac.jp/news.html" target="_blank" rel="noopener noreferrer">YNU AI News</a></span></li></ul></article>
    </div></div></section>`,
  },
  {
    file: "pages/publications.html", active: "publications", title: "Publications | Daimon Sakaguchi",
    description: "Books, peer-reviewed papers, preprints, presentations, and press coverage by Daimon Sakaguchi.",
    body: `<section class="page-hero"><div class="container"><p class="eyebrow">Research Output</p><h1>Publications</h1><p class="lead">Books, journal articles, preprints, presentations, and related press coverage.</p></div></section><section class="section-band"><div class="container content-stack">
      <article><div class="section-heading inline"><p class="section-kicker">Books</p><h2>Books and Book Chapters</h2></div><ol class="publications-list"><li class="publication-item"><p class="publication-status">2026</p><h3>Three-Dimensional Electronic-Field Analysis Governing Reaction Selectivity</h3><p class="publication-meta">Daimon Sakaguchi and Hiroaki Gotoh. In <em>Development of Polymer Materials Using Materials Informatics</em>, Chapter 2, Section 4, pp. 213–225, Technical Information Institute Co., Ltd., July 31, 2026. (Contributed chapter)</p><p>ISBN: 978-4-86798-162-7</p><div class="publication-links"><a href="https://www.gijutu.co.jp/doc/b_2365.htm" target="_blank" rel="noopener noreferrer">Publisher</a></div></li></ol></article>
      <article><div class="section-heading inline"><p class="section-kicker">Preprints</p><h2>Preprints</h2></div><ol class="publications-list"><li class="publication-item"><p class="publication-status">2026</p><h3>Kinetics-Based Framework for Predicting Site- and Facial-Selectivity in Ketone Reductions</h3><p class="publication-meta">Daimon Sakaguchi, Taisei Kawasaki, Mayu Itakura, Chihiro Tada, Hiroaki Gotoh. ChemRxiv, 2026.</p><div class="publication-links"><a href="https://doi.org/10.26434/chemrxiv.15002906/v1" target="_blank" rel="noopener noreferrer">ChemRxiv</a></div></li></ol></article>
      <article id="peer-reviewed-papers"><div class="section-heading inline"><p class="section-kicker">Journal Articles</p><h2>Peer-Reviewed Papers</h2></div><ol class="publications-list">
        <li class="publication-item"><a class="graphical-abstract-link" href="https://doi.org/10.1021/acsomega.5c05523" target="_blank" rel="noopener noreferrer"><img class="graphical-abstract" src="{{ASSETS}}/graphical-abstracts/acs-omega-2025-phenol-coupling.png" alt="Graphical abstract for machine-learning prediction of phenol oxidative homocoupling reactivity" width="520" height="273"></a><p class="publication-status">2025</p><h3>Predicting Substrate Reactivity in Oxidative Homocoupling of Phenols Using Positive and Unlabeled Machine Learning</h3><p class="publication-meta">Takafumi Nishii, Kaname Ichizawa, Haruka Nagano, Hiroya Mukai, Daimon Sakaguchi, Hiroaki Gotoh. ACS Omega 10(42), 49805–49815, 2025.</p><div class="publication-links"><a href="https://doi.org/10.1021/acsomega.5c05523" target="_blank" rel="noopener noreferrer">DOI</a><a href="https://pubmed.ncbi.nlm.nih.gov/41179213/" target="_blank" rel="noopener noreferrer">PubMed</a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC12572977/" target="_blank" rel="noopener noreferrer">PMC</a></div></li>
        <li class="publication-item"><a class="graphical-abstract-link" href="https://doi.org/10.1021/acs.jpca.5c03510" target="_blank" rel="noopener noreferrer"><img class="graphical-abstract" src="{{ASSETS}}/graphical-abstracts/jpca-2025-ketone-reduction.png" alt="Graphical abstract for the three-dimensional electronic-state analysis of asymmetric ketone reduction" width="520" height="196"></a><p class="publication-status">2025</p><h3>Analysis of Asymmetric Reduction of Ketones Using Three-Dimensional Electronic States</h3><p class="publication-meta">Daimon Sakaguchi, Masaki Shimono, Hiroaki Gotoh. The Journal of Physical Chemistry A 129(39), 8945–8958, 2025.</p><div class="publication-links"><a href="https://doi.org/10.1021/acs.jpca.5c03510" target="_blank" rel="noopener noreferrer">DOI</a><a href="https://pubmed.ncbi.nlm.nih.gov/40968668/" target="_blank" rel="noopener noreferrer">PubMed</a><a href="https://pubs.acs.org/doi/abs/10.1021/acs.jpca.5c03510" target="_blank" rel="noopener noreferrer">ACS</a></div></li>
        <li class="publication-item"><a class="graphical-abstract-link" href="https://doi.org/10.1021/acs.jcim.4c00101" target="_blank" rel="noopener noreferrer"><img class="graphical-abstract" src="{{ASSETS}}/graphical-abstracts/jcim-2024-cyclic-ketones.png" alt="Graphical abstract for predicting facial selectivity in nucleophilic additions to cyclic ketones" width="520" height="161"></a><p class="publication-status">2024</p><h3>Using Three-Dimensional Information to Predict and Interpret the Facial Selectivities of Nucleophilic Additions to Cyclic Ketones</h3><p class="publication-meta">Daimon Sakaguchi, Hiroaki Gotoh. Journal of Chemical Information and Modeling 64(8), 3213–3221, 2024.</p><div class="publication-links"><a href="https://doi.org/10.1021/acs.jcim.4c00101" target="_blank" rel="noopener noreferrer">DOI</a><a href="https://pubmed.ncbi.nlm.nih.gov/38591731/" target="_blank" rel="noopener noreferrer">PubMed</a><a href="https://pubs.acs.org/doi/10.1021/acs.jcim.4c00101" target="_blank" rel="noopener noreferrer">ACS</a></div></li>
      </ol></article>
      <article><div class="section-heading inline"><p class="section-kicker">Japanese Article</p><h2>Highlights and Reports</h2></div><ol class="publications-list"><li class="publication-item"><p class="publication-status">2025</p><h3>Elucidating the Origin of Facial Selectivity in Nucleophilic Reactions through Quantitative Evaluation of Stereoelectronic States</h3><p class="publication-meta">Daimon Sakaguchi, Hiroaki Gotoh. Journal of Computer Chemistry, Japan 24(1), A18–A24, 2025. (Japanese)</p><div class="publication-links"><a href="https://doi.org/10.2477/jccj.2024-0043" target="_blank" rel="noopener noreferrer">DOI</a><a href="https://www.jstage.jst.go.jp/article/jccj/24/1/24_2024-0043/_html/-char/ja" target="_blank" rel="noopener noreferrer">J-STAGE</a></div></li></ol></article>
      <article><div class="section-heading inline"><p class="section-kicker">Presentations</p><h2>Recent Presentations</h2></div><ol class="timeline-list compact"><li><time>2026.06</time><span><strong>Prediction and Interpretation of Reaction Selectivity through Data-Driven Analysis of Noncovalent-Interaction Fields in Transition States</strong><br>Daimon Sakaguchi, Masaki Shimono, Hiroaki Gotoh. 2026 Spring Meeting of the Society of Computer Chemistry, Japan, poster 1P05. <a href="https://www.sccj.net/events/nenkai/2026sp/program.html" target="_blank" rel="noopener noreferrer">Program</a></span></li><li><time>2026.06</time><span><strong>Extracting Physical-Organic Principles Inherent in Ketone Reduction through Data-Driven Analysis</strong><br>Mayu Itakura, Taisei Kawasaki, Tomoki Oishi, Daimon Sakaguchi, Hiroaki Gotoh. SCCJ 2026 Spring Meeting, oral presentation 1O06 (coauthor). <a href="https://www.sccj.net/events/nenkai/2026sp/program.html" target="_blank" rel="noopener noreferrer">Program</a></span></li><li><time>2026.02</time><span><strong>Fusion of Transition State Analysis and Data-Driven Approach for Stereoselectivity Prediction in Asymmetric Ketone Reduction</strong><br>Gaussian Workshop, poster.</span></li><li><time>2025.12</time><span><strong>Fusion of Transition State Analysis and Data-Driven Approach for Stereoselectivity Prediction in Asymmetric Ketone Reduction</strong><br>Pacifichem 2025, poster.</span></li><li><time>2025.11</time><span><strong>Analysis of Asymmetric Reduction of Ketones Using Three-Dimensional Electronic States</strong><br>9th Autumn School on Chemoinformatics, poster.</span></li><li><time>2025.09</time><span><strong>Elucidating the Origins of Chemical Reaction Selectivity through Electronic-State Informatics</strong><br>Future Doctoral Festival 2025, poster.</span></li></ol></article>
      <article><div class="section-heading inline"><p class="section-kicker">Press</p><h2>Press and Features</h2></div><ul class="detail-list"><li><strong>Development of a Predictive Model for Chemical Reaction Selectivity through Molecular Electronic-State Analysis</strong><span>Yokohama National University press release, 2024. <a href="https://www.ynu.ac.jp/hus/koho/31704/detail.html" target="_blank" rel="noopener noreferrer">Link</a></span></li><li><strong>Data-Driven Elucidation of Reaction Selectivity by Integrating Machine Learning and Computational Chemistry</strong><span>Chem-Station Spotlight Research, 2024. <a href="https://www.chem-station.com/blog/2024/04/nack.html" target="_blank" rel="noopener noreferrer">Link</a></span></li></ul></article>
    </div></section>`,
  },
];
