import { codeBlock, methodPage } from "./en_method_helpers.mjs";

const pyscf = methodPage({slug:"pyscf",title:"PySCF",eyebrow:"Python-Based Electronic Structure",lead:"Build molecular electronic-structure workflows in Python, from molecule construction and SCF/DFT to geometry optimization and GPU acceleration.",position:"Programmable ab initio and DFT",input:"Python objects, geometry, basis",output:"Energies, density matrices, orbitals",description:"PySCF guide to Mole objects, SCF/DFT, geometry optimization, GPU4PySCF, and Google Colab.",sections:[
  {id:"molecule",title:"Molecule construction",html:`<p>A <code>Mole</code> object defines atoms, units, charge, spin, basis, and symmetry. In PySCF, <code>spin</code> is the number of alpha electrons minus beta electrons, not the multiplicity.</p>${codeBlock("en-pyscf-mol","Python",`from pyscf import gto, dft\n\nmol = gto.M(\n    atom="O 0 0 0; H 0 -0.757 0.587; H 0 0.757 0.587",\n    basis="def2-svp", unit="Angstrom", charge=0, spin=0,\n)\nmf = dft.RKS(mol)\nmf.xc = "PBE0"\nmf.kernel()`)}`},
  {id:"scf",title:"SCF and DFT objects",html:`<p>Choose restricted, unrestricted, or restricted-open-shell references to match the electronic state. Check convergence, orbital occupations, spin, and stability rather than treating a returned energy as sufficient.</p>`},
  {id:"properties",title:"Density matrices and properties",html:`<p><code>make_rdm1()</code> returns a one-particle density matrix. Orbitals, populations, gradients, Hessians, and real-space fields can be accessed from composable Python objects.</p>`},
  {id:"optimization",title:"Geometry optimization",html:`<p>PySCF interfaces with optimizers such as geomeTRIC. Optimize with explicit convergence criteria and verify stationary points with a Hessian or frequency analysis.</p>${codeBlock("en-pyscf-opt","Python",`from pyscf.geomopt.geometric_solver import optimize\noptimized_mol = optimize(mf)`)}`},
  {id:"gpu",title:"GPU4PySCF",html:`<p>GPU4PySCF accelerates supported mean-field, DFT, gradient, and Hessian operations. Confirm feature support, GPU precision, memory use, and numerical agreement with a CPU calculation.</p>${codeBlock("en-pyscf-gpu","Python",`from gpu4pyscf.dft import rks\n\nmf_gpu = rks.RKS(mol, xc="PBE0").density_fit()\nmf_gpu.kernel()`)}`},
  {id:"colab",title:"Google Colab",html:`<p>Colab is useful for reproducible notebooks, but runtime images and GPU availability change. Pin package versions, record the accelerator, and export inputs and results outside the temporary runtime.</p>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://pyscf.org/user.html" target="_blank" rel="noopener noreferrer">PySCF User Guide</a></li><li><a href="https://pyscf.org/user/geomopt.html" target="_blank" rel="noopener noreferrer">Geometry optimization</a></li><li><a href="https://github.com/pyscf/gpu4pyscf" target="_blank" rel="noopener noreferrer">GPU4PySCF</a></li></ul>`},
]});

const psi4 = methodPage({slug:"psi4",title:"Psi4",eyebrow:"Open-Source Quantum Chemistry",lead:"Use Psi4 for interaction-energy analysis with SAPT and for conceptual-DFT quantities such as Fukui functions and the dual descriptor.",position:"Open-source quantum chemistry",input:"Psi4 input or Python API",output:"Energies, SAPT terms, cube fields",description:"Psi4 guide to SAPT interaction-energy decomposition, Fukui functions, dual descriptors, and cubeprop.",sections:[
  {id:"overview",title:"Overview",html:`<p>Psi4 provides a text input language and a Python API. This chapter focuses on SAPT for intermolecular interactions and finite-difference density descriptors for local reactivity.</p>`},
  {id:"sapt",title:"SAPT",html:`<p>Symmetry-adapted perturbation theory partitions an interaction energy into physically motivated components.</p><div class="equation"><math display="block"><msub><mi>E</mi><mrow><mi>int</mi></mrow></msub><mo>≈</mo><msub><mi>E</mi><mrow><mi>elst</mi></mrow></msub><mo>+</mo><msub><mi>E</mi><mrow><mi>exch</mi></mrow></msub><mo>+</mo><msub><mi>E</mi><mrow><mi>ind</mi></mrow></msub><mo>+</mo><msub><mi>E</mi><mrow><mi>disp</mi></mrow></msub></math></div><p>Electrostatics, exchange, induction, and dispersion depend on the chosen SAPT level and grouping convention.</p>${codeBlock("en-psi4-sapt","Psi4 input",`molecule dimer {\n  0 1\n  --\n  0 1\n}\nset { basis jun-cc-pVDZ }\nenergy("sapt0")`)}`},
  {id:"fragments",title:"Fragment definition",html:`<p>Use the <code>--</code> separator to define monomers and assign charge and multiplicity to each fragment. Preserve the dimer geometry when computing an interaction at a fixed structure.</p>`},
  {id:"fukui",title:"Fukui functions",html:`<p>Finite differences of N, N+1, and N-1 electron densities approximate nucleophilic and electrophilic response.</p><div class="equation"><math display="block"><msup><mi>f</mi><mo>+</mo></msup><mo>(</mo><mi>r</mi><mo>)</mo><mo>≈</mo><msub><mi>ρ</mi><mrow><mi>N</mi><mo>+</mo><mn>1</mn></mrow></msub><mo>-</mo><msub><mi>ρ</mi><mi>N</mi></msub><mspace width="1em"/><msup><mi>f</mi><mo>-</mo></msup><mo>(</mo><mi>r</mi><mo>)</mo><mo>≈</mo><msub><mi>ρ</mi><mi>N</mi></msub><mo>-</mo><msub><mi>ρ</mi><mrow><mi>N</mi><mo>-</mo><mn>1</mn></mrow></msub></math></div>`},
  {id:"dual",title:"Dual descriptor",html:`<p>The dual descriptor is <math><mi>Δ</mi><mi>f</mi><mo>(</mo><mi>r</mi><mo>)</mo><mo>=</mo><msup><mi>f</mi><mo>+</mo></msup><mo>-</mo><msup><mi>f</mi><mo>-</mo></msup></math>. Interpret sign conventions explicitly and keep geometry, basis, grid, and electronic-state treatment consistent across charge states.</p>`},
  {id:"cube",title:"Cube output",html:`<p><code>cubeprop</code> writes orbitals, density, electrostatic potential, and related quantities to real-space grids. Record grid spacing, padding, orbital indices, and units.</p>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://psicode.org/psi4manual/master/sapt.html" target="_blank" rel="noopener noreferrer">Psi4 SAPT manual</a></li><li><a href="https://psicode.org/psi4manual/master/cubeprop.html" target="_blank" rel="noopener noreferrer">Psi4 cubeprop</a></li></ul>`},
]});

const orca = methodPage({slug:"orca",title:"ORCA",eyebrow:"Energy Decomposition and Local Correlation",lead:"Define fragments and analyze interaction energies with EDA-NOCV and local energy decomposition while keeping method and fragment conventions explicit.",position:"Electronic structure and EDA",input:"Geometry, fragments, method, basis",output:"Interaction and deformation terms, NOCVs",description:"ORCA guide to fragment interaction energies, EDA-NOCV, local energy decomposition, and interpretation.",sections:[
  {id:"interaction",title:"Interaction energy",html:`<p>At a fixed complex geometry, a basic interaction energy is the energy of the complex minus the energies of isolated fragments evaluated under a defined geometry and basis convention.</p><div class="equation"><math display="block"><msub><mi>ΔE</mi><mrow><mi>int</mi></mrow></msub><mo>=</mo><msub><mi>E</mi><mrow><mi>AB</mi></mrow></msub><mo>-</mo><msub><mi>E</mi><mi>A</mi></msub><mo>-</mo><msub><mi>E</mi><mi>B</mi></msub></math></div>`},
  {id:"fragments",title:"Fragments and preparation",html:`<p>Fragment charge, multiplicity, geometry, orbital reference, and atom assignment are part of the EDA definition. Verify fragment labels in the output before interpreting components.</p>`},
  {id:"eda",title:"EDA-NOCV",html:`<p>EDA separates preparation and interaction terms; EDA-NOCV further resolves orbital interaction through natural orbitals for chemical valence and deformation densities. The exact partition is method-dependent.</p><div class="equation"><math display="block"><msub><mi>ΔE</mi><mrow><mi>int</mi></mrow></msub><mo>=</mo><msub><mi>ΔE</mi><mrow><mi>elstat</mi></mrow></msub><mo>+</mo><msub><mi>ΔE</mi><mrow><mi>Pauli</mi></mrow></msub><mo>+</mo><msub><mi>ΔE</mi><mrow><mi>orb</mi></mrow></msub><mo>+</mo><msub><mi>ΔE</mi><mrow><mi>disp</mi></mrow></msub></math></div>`},
  {id:"nocv",title:"NOCV pairs",html:`<p>Inspect paired eigenvalues and deformation-density plots together. A visual pattern can support a donation or polarization assignment, but the label should be consistent with fragment orbitals and geometry.</p>`},
  {id:"led",title:"Local Energy Decomposition",html:`<p>LED is associated with local-correlation calculations and partitions interaction contributions in a framework different from EDA-NOCV or SAPT. Do not compare similarly named terms as if definitions were identical.</p>`},
  {id:"validation",title:"Validation",html:`<ol><li>Check ORCA version and manual syntax.</li><li>Verify fragment charges, spins, and atom membership.</li><li>State geometry and basis conventions.</li><li>Inspect SCF and correlation convergence.</li><li>Compare total interaction energies before individual terms.</li></ol>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://www.faccts.de/docs/orca/6.1/manual/" target="_blank" rel="noopener noreferrer">ORCA 6.1 Manual</a></li><li><a href="https://www.faccts.de/docs/orca/6.1/manual/contents/modelchemistries/energydecomposition.html" target="_blank" rel="noopener noreferrer">ORCA energy decomposition</a></li></ul>`},
]});

const cube = methodPage({slug:"cube",title:"Cube Files",eyebrow:"Volumetric Data on a Three-Dimensional Grid",lead:"Store atomic coordinates and scalar values on a three-dimensional grid to connect electronic-structure calculations, real-space analysis, and visualization.",position:"Exchange format for 3D fields",input:"Density, MO, ESP, spin density, RDG",output:"ASCII grid and molecular geometry",description:"Guide to Gaussian cube structure, grids, units, density, orbitals, electrostatic potential, arithmetic, and visualization.",sections:[
  {id:"overview",title:"What a cube file stores",html:`<p>A cube file is a container, not a physical observable. Its values may represent electron density, a molecular orbital, electrostatic potential, spin density, or an analysis field. Save the field definition and generation command with the file.</p>`},
  {id:"structure",title:"File structure",html:`<p>The format contains two comment lines, atom count and grid origin, three grid axes, atom records, and voxel values. Axis vectors need not be parallel to the Cartesian axes.</p>${codeBlock("en-cube-format","Cube skeleton",`comment line 1\ncomment line 2\nN_atoms  origin_x origin_y origin_z\nN_x      dx_x dx_y dx_z\nN_y      dy_x dy_y dy_z\nN_z      dz_x dz_y dz_z\nZ_1      q_1  x_1 y_1 z_1\n...\nvoxel values`)}`},
  {id:"grid",title:"Grid coordinates and units",html:`<div class="equation"><math display="block"><mi>r</mi><mo>(</mo><mi>i</mi><mo>,</mo><mi>j</mi><mo>,</mo><mi>k</mi><mo>)</mo><mo>=</mo><msub><mi>r</mi><mn>0</mn></msub><mo>+</mo><mi>i</mi><msub><mi>a</mi><mn>1</mn></msub><mo>+</mo><mi>j</mi><msub><mi>a</mi><mn>2</mn></msub><mo>+</mo><mi>k</mi><msub><mi>a</mi><mn>3</mn></msub></math></div><p>Confirm the producer's unit convention. Halving the spacing approximately doubles each dimension and increases the total voxel count about eightfold.</p>`},
  {id:"fields",title:"Physical fields",html:`<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Field</th><th>Important property</th></tr></thead><tbody><tr><td>Electron density</td><td>Normally nonnegative; its integral relates to electron count</td></tr><tr><td>Molecular orbital</td><td>Signed amplitude, not an electron density</td></tr><tr><td>Spin density</td><td>Difference between alpha and beta densities</td></tr><tr><td>Electrostatic potential</td><td>Often mapped onto a density isosurface</td></tr></tbody></table></div>`},
  {id:"generation",title:"Generation",html:`<p>Gaussian uses <code>formchk</code> and <code>cubegen</code>; PySCF provides <code>pyscf.tools.cubegen</code>; ORCA uses <code>%plots</code> or <code>orca_plot</code>; Multiwfn can export many wavefunction-derived fields.</p>${codeBlock("en-cube-pyscf","PySCF",`from pyscf.tools import cubegen\n\ndm = mf.make_rdm1()\ncubegen.density(mol, "density.cube", dm, resolution=0.20)\ncubegen.mep(mol, "esp.cube", dm, resolution=0.20)`)}`},
  {id:"operations",title:"Arithmetic on cube data",html:`<p>Pointwise differences require identical origins, axis vectors, shapes, units, geometries, and field definitions.</p><div class="equation"><math display="block"><mi>Δρ</mi><mo>(</mo><mi>r</mi><mo>)</mo><mo>=</mo><msub><mi>ρ</mi><mrow><mi>AB</mi></mrow></msub><mo>-</mo><msub><mi>ρ</mi><mi>A</mi></msub><mo>-</mo><msub><mi>ρ</mi><mi>B</mi></msub></math></div><div class="callout warning"><strong>Prefer regeneration to interpolation</strong><p>Generate all fields on the same explicit grid whenever possible. Interpolation introduces numerical and boundary errors.</p></div>`},
  {id:"visualization",title:"Visualization and validation",html:`<p>Use equal positive and negative isovalues for signed orbitals, fixed color ranges for comparisons, and record every isovalue. Verify voxel count, margins, field integrals where applicable, and the mapping between geometry and field.</p><p>Continue to <a href="multiwfn.html">Multiwfn</a>, <a href="nciplot.html">NCIplot</a>, or <a href="py3dmol.html">py3Dmol</a>.</p>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://pyscf.org/pyscf_api_docs/pyscf.tools.html" target="_blank" rel="noopener noreferrer">PySCF cubegen API</a></li><li><a href="https://www.faccts.de/docs/orca/6.1/manual/contents/utilitiesvisualization/plots.html" target="_blank" rel="noopener noreferrer">ORCA plots</a></li><li><a href="https://h5cube-spec.readthedocs.io/en/latest/cubeformat.html" target="_blank" rel="noopener noreferrer">Cube format specification</a></li></ul>`},
]});

const multiwfn = methodPage({slug:"multiwfn",title:"Multiwfn",eyebrow:"Real-Space Wavefunction Analysis",lead:"Analyze electron density and its derivatives with NCI, IGM, IGMH, and IRI to visualize spatial patterns associated with molecular interactions.",position:"Wavefunction and real-space analysis",input:"fchk, wfn/wfx, molden, cube, XYZ",output:"Grid data, cube, critical points",description:"Multiwfn guide to NCI, IGM, IGMH, IRI, fragment definitions, cube output, and interpretation.",sections:[
  {id:"overview",title:"Scope",html:`<p>Multiwfn analyzes orbitals, density, electrostatic potential, topology, populations, and many real-space functions. This chapter focuses on interaction-region visualization.</p><div class="callout warning"><strong>Visualization is not an energy decomposition</strong><p>The presence, area, or color of an isosurface does not directly provide an interaction energy.</p></div>`},
  {id:"nci",title:"NCI and reduced density gradient",html:`<p>NCI analysis identifies low-density, low-gradient regions using the reduced density gradient.</p><div class="equation"><math display="block"><mi>s</mi><mo>(</mo><mi>r</mi><mo>)</mo><mo>=</mo><mfrac><mn>1</mn><mrow><mn>2</mn><msup><mfenced><mrow><mn>3</mn><msup><mi>π</mi><mn>2</mn></msup></mrow></mfenced><mrow><mn>1</mn><mo>/</mo><mn>3</mn></mrow></msup></mrow></mfrac><mfrac><mrow><mo>|</mo><mo>∇</mo><mi>ρ</mi><mo>|</mo></mrow><msup><mi>ρ</mi><mrow><mn>4</mn><mo>/</mo><mn>3</mn></mrow></msup></mfrac></math></div><p>Surfaces are commonly colored by <code>sign(lambda2)rho</code> to distinguish attractive-like and repulsive-like regions qualitatively.</p>`},
  {id:"igm",title:"IGM",html:`<p>The independent gradient model compares an upper-bound gradient constructed from independent atomic contributions with the actual molecular-density gradient. The difference highlights regions where gradients cancel.</p>`},
  {id:"igmh",title:"IGMH",html:`<p>IGMH uses the actual molecular density in an IGM-like framework and can separate interfragment and intrafragment contributions. Fragment definitions are therefore part of the analysis.</p>`},
  {id:"iri",title:"IRI",html:`<p>The interaction region indicator is designed to reveal covalent and noncovalent interaction regions in a unified representation. Isovalue and color scale must be stated when comparing systems.</p>`},
  {id:"workflow",title:"Practical workflow",html:`<ol><li>Load a wavefunction file and verify geometry.</li><li>Choose the real-space function and fragment definition.</li><li>Set grid range, spacing, and cutoff.</li><li>Export shape and coloring cubes.</li><li>Visualize with fixed settings across the series.</li><li>Relate patterns to independent energetic or experimental evidence.</li></ol>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://sobereva.com/multiwfn/" target="_blank" rel="noopener noreferrer">Multiwfn official site</a></li><li><a href="https://sobereva.com/multiwfn/misc/Multiwfn%20quick%20start.pdf" target="_blank" rel="noopener noreferrer">Multiwfn quick start</a></li><li><a href="https://doi.org/10.1002/wcms.1448" target="_blank" rel="noopener noreferrer">Multiwfn review</a></li></ul>`},
]});

const nciplot = methodPage({slug:"nciplot",title:"NCIplot",eyebrow:"Noncovalent Interaction Plot",lead:"Generate reduced-density-gradient and signed-density data from wavefunction or promolecular densities with a program dedicated to NCI analysis.",position:"Dedicated real-space NCI analysis",input:"wfn/wfx or XYZ and NCI input",output:"Density/RDG cubes, data, VMD script",description:"NCIplot guide to density models, input, grids, cutoffs, cube output, VMD, and interpretation.",sections:[
  {id:"density",title:"Density models",html:`<p>Wavefunction-derived density uses wfn/wfx data, whereas promolecular density sums independent atomic densities from an XYZ geometry. The latter is fast but does not include molecular density relaxation.</p>`},
  {id:"input",title:"Input and execution",html:`<p>An NCI input specifies the molecule, density source, grid, and cutoffs. Keep input and geometry together and record the NCIplot version.</p>${codeBlock("en-nciplot-run","Shell",`nciplot water-dimer.nci > water-dimer.out`)}`},
  {id:"grid",title:"Grid and cutoffs",html:`<p>The grid must contain the interaction region with adequate spacing. Density and RDG cutoffs control which points and surfaces are retained; changing them changes the visual result.</p>`},
  {id:"outputs",title:"Output files",html:`<p>Typical outputs include density and RDG cube files, scatter-plot data, and a VMD script. Associate each file with the generating input to avoid mixing grids or color fields.</p>`},
  {id:"visualization",title:"VMD visualization",html:`<p>Use the RDG cube for surface geometry and signed density for coloring. Fix isovalue and color range when comparing a molecular series.</p>`},
  {id:"interpretation",title:"Interpretation",html:`<p>NCI surfaces identify regions compatible with weak interactions, steric contacts, or density overlap. They do not uniquely assign an interaction type or quantify its energy.</p>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://github.com/aoterodelaroza/nciplot" target="_blank" rel="noopener noreferrer">NCIplot repository</a></li><li><a href="https://doi.org/10.1021/ct100641a" target="_blank" rel="noopener noreferrer">NCIplot program paper</a></li></ul>`},
]});

const py3dmol = methodPage({slug:"py3dmol",title:"py3Dmol",eyebrow:"Interactive Molecular Visualization",lead:"Display structures, conformers, labels, and cube isosurfaces interactively in Jupyter notebooks and Google Colab.",position:"Notebook and web molecular viewer",input:"XYZ, SDF/MOL, PDB, cube",output:"Interactive WebGL visualization",description:"py3Dmol guide to molecular structures, RDKit conformers, labels, styles, and cube isosurfaces.",sections:[
  {id:"setup",title:"Setup",html:`<p>py3Dmol wraps 3Dmol.js in a notebook-friendly Python API. The rendered viewer is browser-side WebGL; save the source structure and viewing parameters alongside screenshots.</p>${codeBlock("en-py3dmol-setup","Python",`import py3Dmol\n\nview = py3Dmol.view(width=640, height=480)\nview.addModel(xyz_text, "xyz")\nview.setStyle({"stick": {}, "sphere": {"scale": 0.25}})\nview.zoomTo()\nview.show()`)}`},
  {id:"formats",title:"XYZ, SDF, and PDB",html:`<p>XYZ supplies coordinates but normally lacks bond orders. SDF/MOL carries connectivity and properties; PDB supports biomolecular records. Choose a format that preserves the information needed for the figure.</p>`},
  {id:"rdkit",title:"RDKit integration",html:`<p>Convert an RDKit conformer to a Mol block and add it with <code>addModel</code>. Explicitly choose the conformer ID and hydrogen treatment.</p>${codeBlock("en-py3dmol-rdkit","Python",`from rdkit import Chem\n\nmolblock = Chem.MolToMolBlock(mol, confId=0)\nview.addModel(molblock, "mol")`)}`},
  {id:"styles",title:"Styles and labels",html:`<p>Use stick, line, sphere, and cartoon styles for different tasks. Atom labels, selections, and colors should convey chemical information rather than decoration.</p>`},
  {id:"conformers",title:"Conformer comparison",html:`<p>Use separate viewers or models with controlled alignment to compare conformers. Do not imply that an unweighted set of displayed conformers is a thermodynamic population.</p>`},
  {id:"cube",title:"Cube isosurfaces",html:`<p>Add volumetric data and render positive and negative surfaces separately for signed orbitals. For electrostatic potential mapping or NCI coloring, keep the shape field and color field conceptually distinct.</p>`},
  {id:"qa",title:"Web-display checks",html:`<ol><li>Confirm a nonblank canvas.</li><li>Check framing after <code>zoomTo()</code>.</li><li>Test mouse rotation and zoom.</li><li>Verify colors and isovalues.</li><li>Inspect desktop and mobile dimensions.</li></ol>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://3dmol.csb.pitt.edu/doc/" target="_blank" rel="noopener noreferrer">3Dmol.js documentation</a></li><li><a href="https://pypi.org/project/py3Dmol/" target="_blank" rel="noopener noreferrer">py3Dmol package</a></li></ul>`},
]});

export const methodPagesCore2 = [pyscf, psi4, orca, cube, multiwfn, nciplot, py3dmol];
