import { codeBlock, methodPage } from "./en_method_helpers.mjs";

const cheminformatics = methodPage({slug:"cheminformatics",title:"RDKit Cheminformatics",eyebrow:"Chemical Identity, Search and Molecular Features",lead:"Identify molecules, search by substructure and similarity, and transform atomic and molecular information into tabular features for data analysis.",position:"Chemical information processing",input:"SMILES, SDF, MOL, CSV",output:"InChIKey, fingerprints, descriptors, SVG",type:"data",description:"RDKit guide to InChIKey, standardization, descriptors, Gasteiger charges, fingerprints, SMARTS, and depiction.",sections:[
  {id:"overview",title:"Workflow",html:`<p>A typical cheminformatics workflow is <span class="formula-inline">read -> sanitize -> standardize -> identify -> featurize -> search/model</span>. Decide first whether salts, isotopes, stereoisomers, tautomers, and protonation states count as the same compound.</p>`},
  {id:"identity",title:"SMILES, InChI, and InChIKey",html:`<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Representation</th><th>Role</th></tr></thead><tbody><tr><td>Canonical SMILES</td><td>Toolkit-canonicalized graph string</td></tr><tr><td>Isomeric SMILES</td><td>SMILES retaining specified isotope and stereochemical information</td></tr><tr><td>Standard InChI</td><td>Layered standardized identifier</td></tr><tr><td>InChIKey</td><td>Fixed-length, irreversible hash for lookup</td></tr></tbody></table></div>${codeBlock("en-cheminf-id","Python",`from rdkit import Chem\nfrom rdkit.Chem import inchi\n\nmol = Chem.MolFromSmiles("C[C@H](O)C(=O)O")\nsmiles = Chem.MolToSmiles(mol, isomericSmiles=True)\ninchi_text = inchi.MolToInchi(mol)\ninchi_key = inchi.InchiToInchiKey(inchi_text)`)}`},
  {id:"standardization",title:"Structure standardization",html:`<p>Standardization applies project-specific rules; it does not discover a uniquely correct structure. Cleanup, fragment selection, uncharging, and tautomer canonicalization can remove information relevant to measured salt forms or pH conditions.</p>${codeBlock("en-cheminf-std","Python",`from rdkit.Chem.MolStandardize import rdMolStandardize\n\nclean = rdMolStandardize.Cleanup(raw_mol)\nparent = rdMolStandardize.FragmentParent(clean)\nneutral = rdMolStandardize.Uncharger().uncharge(parent)`)}`},
  {id:"descriptors",title:"Descriptors and Gasteiger charges",html:`<p>Molecular weight, LogP, TPSA, hydrogen-bond counts, rotatable bonds, and rings compress graph information into scalar descriptors. Gasteiger charges are fast empirical partial charges and are not interchangeable with Mulliken, NPA, or Hirshfeld populations.</p>${codeBlock("en-cheminf-charge","Python",`from rdkit.Chem import AllChem, Descriptors\n\nAllChem.ComputeGasteigerCharges(mol)\ncharges = [a.GetDoubleProp("_GasteigerCharge") for a in mol.GetAtoms()]\nfeatures = {"MolWt": Descriptors.MolWt(mol),\n            "LogP": Descriptors.MolLogP(mol),\n            "TPSA": Descriptors.TPSA(mol)}`)}`},
  {id:"fingerprints",title:"Fingerprints and similarity",html:`<p>Morgan, RDKit topological, and MACCS fingerprints encode different structural features. For bit vectors, Tanimoto similarity is</p><div class="equation"><math display="block"><mi>T</mi><mo>(</mo><mi>A</mi><mo>,</mo><mi>B</mi><mo>)</mo><mo>=</mo><mfrac><msub><mi>n</mi><mrow><mi>AB</mi></mrow></msub><mrow><msub><mi>n</mi><mi>A</mi></msub><mo>+</mo><msub><mi>n</mi><mi>B</mi></msub><mo>-</mo><msub><mi>n</mi><mrow><mi>AB</mi></mrow></msub></mrow></mfrac></math></div>${codeBlock("en-cheminf-fp","Python",`from rdkit import DataStructs\nfrom rdkit.Chem import rdFingerprintGenerator\n\ngen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)\nfps = [gen.GetFingerprint(m) for m in mols]\nsim = DataStructs.TanimotoSimilarity(fps[0], fps[1])`)}<p>Similarity values are meaningful only together with fingerprint type, radius, size, and feature settings.</p>`},
  {id:"substructure",title:"SMARTS substructure searching",html:`<p>SMARTS represents a query rather than one molecule. Specify aromaticity, formal charge, valence, hydrogen, ring, and stereochemical constraints needed by the chemical question.</p>${codeBlock("en-cheminf-smarts","Python",`amide = Chem.MolFromSmarts("[NX3][CX3](=[OX1])")\nmatches = target.GetSubstructMatches(amide, useChirality=True)`)}`},
  {id:"drawing",title:"Depiction and highlighting",html:`<p>Highlight matched atoms and bonds, align a common core across a molecular series, and include the color scale and sign when visualizing atomic contributions such as Gasteiger charges.</p>`},
  {id:"dataset",title:"Dataset construction",html:`<ol><li>Retain source structures and identifiers.</li><li>Record parse failures and mixtures.</li><li>Generate standardized SMILES and InChIKeys.</li><li>Fix descriptor definitions and RDKit version.</li><li>Check missing, infinite, and near-constant features.</li><li>Match structures to target units and measurement conditions.</li><li>Consider scaffold or series splits in addition to random splits.</li></ol><p>Continue to <a href="data-analysis.html">numerical and statistical analysis</a>.</p>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://www.rdkit.org/docs/GettingStartedInPython.html" target="_blank" rel="noopener noreferrer">Getting Started with RDKit in Python</a></li><li><a href="https://www.rdkit.org/docs/RDKit_Book.html" target="_blank" rel="noopener noreferrer">The RDKit Book</a></li><li><a href="https://www.rdkit.org/docs/source/rdkit.Chem.inchi.html" target="_blank" rel="noopener noreferrer">RDKit InChI API</a></li></ul>`},
]});

const dataAnalysis = methodPage({slug:"data-analysis",title:"Numerical Analysis and Machine Learning",eyebrow:"Matrices, Regularized Regression and Interpretation",lead:"Define molecules or reactions as rows and descriptors as columns, then apply reproducible preprocessing, regularized regression, dimensionality reduction, and model interpretation.",position:"NumPy and linear algebra",input:"Feature matrix X and target y",output:"Predictions, coefficients, scores, SHAP",type:"data",description:"Guide to NumPy matrices, Ridge, Lasso, Elastic Net, cross-validation, PCA, and SHAP for chemical data.",sections:[
  {id:"matrix",title:"Chemical data as a matrix",html:`<p>For n molecules or reactions and p features, define <math><mi>X</mi><mo>∈</mo><msup><mi>R</mi><mrow><mi>n</mi><mo>×</mo><mi>p</mi></mrow></msup></math> and a target vector <math><mi>y</mi><mo>∈</mo><msup><mi>R</mi><mi>n</mi></msup></math>. Columns may contain physicochemical descriptors, fingerprint bits, Sterimol parameters, buried volumes, or field features.</p>`},
  {id:"numpy",title:"NumPy arrays and linear algebra",html:`<p>Use <code>ndarray</code> rather than <code>numpy.matrix</code>. The <code>*</code> operator is elementwise multiplication and <code>@</code> is matrix multiplication.</p>${codeBlock("en-data-numpy","Python",`import numpy as np\n\nprint(X.shape)\ngram = X.T @ X\nbeta, residuals, rank, singular = np.linalg.lstsq(X, y, rcond=None)`)}`},
  {id:"least-squares",title:"Least squares and conditioning",html:`<div class="equation"><math display="block"><mover><mi>β</mi><mo>^</mo></mover><mo>=</mo><munder><mo>arg min</mo><mi>β</mi></munder><msubsup><mrow><mo>∥</mo><mi>y</mi><mo>-</mo><mi>X</mi><mi>β</mi><mo>∥</mo></mrow><mn>2</mn><mn>2</mn></msubsup></math></div><p>Avoid explicitly forming an inverse of <math><msup><mi>X</mi><mi>T</mi></msup><mi>X</mi></math>. Use least-squares, QR, SVD, or tested estimators. Large condition numbers indicate scale differences or collinearity.</p>`},
  {id:"regularization",title:"Ridge, Lasso, and Elastic Net",html:`<p>Ridge applies an L2 penalty and shrinks correlated coefficients smoothly. Lasso applies an L1 penalty and can produce sparse coefficients, but may select one of several correlated descriptors unstably. Elastic Net combines both.</p><div class="equation"><math display="block"><munder><mo>min</mo><mi>β</mi></munder><mfrac><mn>1</mn><mrow><mn>2</mn><mi>n</mi></mrow></mfrac><msubsup><mrow><mo>∥</mo><mi>y</mi><mo>-</mo><mi>X</mi><mi>β</mi><mo>∥</mo></mrow><mn>2</mn><mn>2</mn></msubsup><mo>+</mo><mi>α</mi><mi>ρ</mi><msub><mrow><mo>∥</mo><mi>β</mi><mo>∥</mo></mrow><mn>1</mn></msub><mo>+</mo><mfrac><mrow><mi>α</mi><mo>(</mo><mn>1</mn><mo>-</mo><mi>ρ</mi><mo>)</mo></mrow><mn>2</mn></mfrac><msubsup><mrow><mo>∥</mo><mi>β</mi><mo>∥</mo></mrow><mn>2</mn><mn>2</mn></msubsup></math></div>${codeBlock("en-data-enet","scikit-learn",`from sklearn.linear_model import ElasticNetCV\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\n\nmodel = make_pipeline(\n    StandardScaler(),\n    ElasticNetCV(l1_ratio=[0.1, 0.5, 0.9, 1.0], cv=5),\n)\nmodel.fit(X_train, y_train)`)}`},
  {id:"validation",title:"Splits, preprocessing, and metrics",html:`<p>Put scaling, imputation, and feature selection inside a Pipeline so that each validation fold learns preprocessing only from its training partition. Random splitting can overestimate performance when related scaffolds or catalyst series occur in both sets; design group splits around the intended extrapolation task.</p><p>Report MAE, RMSE, R2, baselines, sample counts, uncertainty, and applicability domain.</p>`},
  {id:"pca",title:"Principal component analysis",html:`<p>PCA projects centered data onto orthogonal directions of maximum variance. scikit-learn centers but does not scale inputs, so descriptors with different units usually require standardization.</p>${codeBlock("en-data-pca","scikit-learn",`from sklearn.decomposition import PCA\nfrom sklearn.preprocessing import StandardScaler\n\nX_scaled = StandardScaler().fit_transform(X)\npca = PCA(n_components=0.95)\nscores = pca.fit_transform(X_scaled)\nloadings = pca.components_.T`)}<p>Scores locate samples; loadings describe feature directions. A component's overall sign may be reversed without changing the solution.</p>`},
  {id:"shap",title:"SHAP",html:`<p>SHAP decomposes a model output into a baseline and feature contributions.</p><div class="equation"><math display="block"><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><msub><mi>ϕ</mi><mn>0</mn></msub><mo>+</mo><munderover><mo>∑</mo><mrow><mi>j</mi><mo>=</mo><mn>1</mn></mrow><mi>p</mi></munderover><msub><mi>ϕ</mi><mi>j</mi></msub></math></div><p>Beeswarm plots summarize a dataset; waterfall plots explain one prediction; scatter plots show feature-value relationships. Attribution depends on the model, background distribution, and treatment of correlated features.</p><div class="callout warning"><strong>Prediction is not causation</strong><p>SHAP explains a predictive model. It does not by itself show that manipulating a descriptor will change selectivity.</p></div>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://numpy.org/doc/stable/user/index.html" target="_blank" rel="noopener noreferrer">NumPy User Guide</a></li><li><a href="https://scikit-learn.org/stable/modules/linear_model.html" target="_blank" rel="noopener noreferrer">scikit-learn linear models</a></li><li><a href="https://scikit-learn.org/stable/modules/decomposition.html" target="_blank" rel="noopener noreferrer">scikit-learn PCA</a></li><li><a href="https://shap.readthedocs.io/en/stable/api.html" target="_blank" rel="noopener noreferrer">SHAP documentation</a></li></ul>`},
]});

const steric = methodPage({slug:"steric-descriptors",title:"Steric Descriptors and Three-Dimensional Fields",eyebrow:"Molecular Shape, Catalytic Pockets and 3D Fields",lead:"Quantify molecular size as directional widths, occupied volume around a reactive center, and spatial fields, then relate those representations to reaction selectivity.",position:"Sterimol L, B1, and B5",input:"3D conformers and aligned fields",output:"%Vbur, steric maps, feature matrices",type:"data",description:"Guide to Sterimol, percent buried volume, steric maps, conformer averaging, 3D electronic fields, and selectivity analysis.",sections:[
  {id:"representations",title:"Representing steric effects",html:`<p>Steric effects are directional. Sterimol retains dimensions along a specified axis, %Vbur measures total occupancy around a center, quadrant volumes retain coarse asymmetry, and steric maps or voxel fields preserve spatial distributions.</p>`},
  {id:"sterimol",title:"Sterimol L, B1, and B5",html:`<ul><li><strong>L:</strong> length along the primary attachment axis.</li><li><strong>B1:</strong> minimum width perpendicular to that axis.</li><li><strong>B5:</strong> maximum width perpendicular to that axis.</li></ul><p>Some software uses Bmin/Bmax. Coordinates, atom order, reference-axis direction, van der Waals radii, and hydrogen treatment are part of the descriptor definition.</p>`},
  {id:"conformers",title:"Conformer dependence",html:`<p>For flexible substituents, one minimum does not represent the descriptor distribution. Compute values across a conformer ensemble and report distributions or Boltzmann-weighted summaries.</p><div class="equation"><math display="block"><msub><mi>w</mi><mi>i</mi></msub><mo>=</mo><mfrac><mrow><mi>exp</mi><mo>[</mo><mo>-</mo><mi>Δ</mi><msub><mi>G</mi><mi>i</mi></msub><mo>/</mo><mo>(</mo><mi>R</mi><mi>T</mi><mo>)</mo><mo>]</mo></mrow><mrow><munderover><mo>∑</mo><mi>j</mi><mi>N</mi></munderover><mi>exp</mi><mo>[</mo><mo>-</mo><mi>Δ</mi><msub><mi>G</mi><mi>j</mi></msub><mo>/</mo><mo>(</mo><mi>R</mi><mi>T</mi><mo>)</mo><mo>]</mo></mrow></mfrac></math></div>`},
  {id:"vbur",title:"Percent buried volume",html:`<p>%Vbur is the fraction of a sphere centered on a metal or putative reactive site that is occupied by ligand van der Waals volume.</p><div class="equation"><math display="block"><mo>%</mo><msub><mi>V</mi><mrow><mi>bur</mi></mrow></msub><mo>=</mo><mn>100</mn><mo>×</mo><mfrac><msub><mi>V</mi><mrow><mi>occupied</mi></mrow></msub><mrow><mn>4</mn><mi>π</mi><msup><mi>R</mi><mn>3</mn></msup><mo>/</mo><mn>3</mn></mrow></mfrac></math></div><p>Sphere center, radius, metal-ligand distance, excluded atoms, hydrogens, radii scaling, and grid spacing must be fixed for comparisons.</p>`},
  {id:"map",title:"Steric maps and quadrants",html:`<p>Place the reactive center at the origin, align the coordination or reaction axis with z, fix x/y orientation using chemically corresponding references, remove excluded atoms, and generate all maps with the same radius, mesh, radii, and color scale.</p><div class="callout warning"><strong>Orientation is data</strong><p>Rotation or reflection inconsistencies invalidate quadrant and pixelwise comparisons.</p></div>`},
  {id:"tools",title:"DBSTEP and SambVca",html:`<p>DBSTEP calculates Sterimol, %Vbur, Sterimol2Vec, and Vol2Vec from 3D structures. SambVca provides buried volumes and topographic steric maps.</p>${codeBlock("en-steric-dbstep","Shell",`python -m dbstep conformer.xyz --sterimol --atom1 2 --atom2 5\npython -m dbstep conformer.xyz --volume --atom1 2 --radius 3.5`)}<p>Check option names against the installed version and store all reference-atom definitions.</p>`},
  {id:"fields",title:"Extension to three-dimensional electronic fields",html:`<p>Sterimol and %Vbur mainly describe van der Waals shape. Electrostatic potential, density deformation, frontier-orbital fields, and NCI/IGMH/IRI fields can add electronic and interaction information on a common aligned grid.</p><p>See the <a href="cube.html">cube chapter</a> for grids and the <a href="multiwfn.html">Multiwfn chapter</a> for real-space functions. Since voxel count greatly exceeds sample count, use masks, regional integration, PCA, or regularization.</p>`},
  {id:"selectivity",title:"Connecting descriptors to selectivity",html:`<p>Enantioselectivity can be transformed to a free-energy difference under a fixed sign and temperature convention.</p><div class="equation"><math display="block"><mi>ΔΔ</mi><msup><mi>G</mi><mo>‡</mo></msup><mo>=</mo><mo>-</mo><mi>R</mi><mi>T</mi><mi>ln</mi><mfenced><mfrac><mrow><mn>1</mn><mo>+</mo><mi>ee</mi></mrow><mrow><mn>1</mn><mo>-</mo><mi>ee</mi></mrow></mfrac></mfenced></math></div><ol><li>Define a common reactive coordinate system.</li><li>Generate conformer ensembles consistently.</li><li>Calculate shape and field features with fixed definitions.</li><li>Evaluate scaling, correlation, and conformer uncertainty.</li><li>Use grouped validation for new substrate or catalyst series.</li><li>Compare statistical interpretations with transition states and experiments.</li></ol>`},
  {id:"references",title:"References",html:`<ul class="reference-list"><li><a href="https://pubs.acs.org/doi/10.1021/acscatal.8b04043" target="_blank" rel="noopener noreferrer">Conformational effects on Sterimol descriptors</a></li><li><a href="https://pypi.org/project/dbstep/" target="_blank" rel="noopener noreferrer">DBSTEP</a></li><li><a href="https://www.aocdweb.com/OMtools/sambvca2.1/info/info.html" target="_blank" rel="noopener noreferrer">SambVca 2.1</a></li><li><a href="https://doi.org/10.1021/acs.organomet.6b00371" target="_blank" rel="noopener noreferrer">SambVca 2 and topographic steric maps</a></li></ul>`},
]});

export const methodPagesData = [cheminformatics, dataAnalysis, steric];
