const additions = {
  state: `<p>The wavefunction depends on all spatial and spin coordinates. The general density definition therefore uses the absolute square of the wavefunction and a sum over the retained electron's spin:</p><div class="equation"><math display="block"><mi>ρ</mi><mo>(</mo><mi>r</mi><mo>)</mo><mo>=</mo><mi>N</mi><munderover><mo>∑</mo><msub><mi>σ</mi><mn>1</mn></msub><mtext>spin</mtext></munderover><mo>∫</mo><msup><mfenced open="|" close="|"><mi>Ψ</mi><mo>(</mo><mi>r</mi><mo>,</mo><msub><mi>σ</mi><mn>1</mn></msub><mo>,</mo><msub><mi>x</mi><mn>2</mn></msub><mo>,</mo><mo>…</mo><mo>,</mo><msub><mi>x</mi><mi>N</mi></msub><mo>)</mo></mfenced><mn>2</mn></msup><mi>d</mi><msub><mi>x</mi><mn>2</mn></msub><mo>…</mo><mi>d</mi><msub><mi>x</mi><mi>N</mi></msub></math></div><p>Its integral over all space is the number of electrons. Density, spin density, orbital amplitude, electrostatic potential, and reduced density gradient are distinct fields even when all are stored in cube files.</p>`,
  bo: `<p>The approximation separates electronic and nuclear motion, but it does not make nuclei stationary in reality. Breakdown can matter near degeneracies, conical intersections, and strongly nonadiabatic processes.</p><div class="callout warning"><strong>Every energy is conditional</strong><p>Geometry, charge, multiplicity, method, basis, solvent, numerical grid, and convergence settings are part of its definition.</p></div>`,
  scf: `<p>Hartree-Fock uses one Slater determinant: exchange is included within that determinant, while dynamical electron correlation is omitted. Kohn-Sham DFT uses orbitals that reproduce the density and places unknown many-body effects in an approximate exchange-correlation functional.</p><ol><li>Build the matrix from a trial density.</li><li>Solve the generalized eigenvalue problem.</li><li>Construct a new density from occupied orbitals.</li><li>Mix the update and iterate to convergence.</li></ol><p>Check occupations, the intended state, spin contamination for unrestricted references, and wavefunction stability when relevant.</p>`,
  basis: `<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Choice</th><th>Purpose</th><th>Caution</th></tr></thead><tbody><tr><td>Polarization</td><td>Angular deformation of density</td><td>Important for bonding changes and anisotropic interactions</td></tr><tr><td>Diffuse functions</td><td>Spatially extended density</td><td>Important for anions and weak binding; may cause linear dependence</td></tr><tr><td>Effective core potentials</td><td>Replace core electrons</td><td>Pair with the intended valence basis and relativistic treatment</td></tr></tbody></table></div><p>Interaction energies can suffer from basis-set superposition error. Counterpoise correction and basis enlargement address different aspects of basis incompleteness and must be documented.</p>`,
  dft: `<p>Hybrid, range-separated, meta-GGA, and double-hybrid functionals make different approximations and have different costs. Dispersion corrections, integration grids, delocalization error, and the chemical domain all affect reliability. Benchmark the protocol when small selectivity differences are the target.</p>`,
  surface: `<p>An optimization locates a nearby stationary point rather than a guaranteed global minimum. A minimum normally has no significant imaginary mode; a first-order saddle point normally has one. Visualize that mode and use IRC or another path-following method to verify both endpoints.</p><p>Thermal corrections depend on the harmonic approximation, low-frequency treatment, temperature, pressure, standard state, and conformer populations.</p>`,
  interactions: `<p>Real-space plots are sensitive to density source, grid, isovalue, color range, and fragment definition. A surface may support a mechanistic interpretation, but it does not uniquely label an interaction or provide its energy.</p><p>For reaction selectivity, connect rate ratios to activation free-energy differences under a stated sign and temperature convention, include relevant conformers and pathways, and compare against independent energetic or experimental evidence.</p>`,
  reproducibility: `<ol><li>Confirm geometry, atom order, charge, multiplicity, and intended state.</li><li>Confirm SCF and geometry convergence.</li><li>Classify stationary points with frequencies.</li><li>Verify transition-state connectivity.</li><li>Check conformer and pathway coverage.</li><li>Preserve inputs, outputs, versions, and post-processing commands.</li></ol><ul class="reference-list"><li><a href="https://doi.org/10.1103/PhysRev.140.A1133" target="_blank" rel="noopener noreferrer">Kohn-Sham equations</a></li><li><a href="https://doi.org/10.1021/ja100936w" target="_blank" rel="noopener noreferrer">Noncovalent-interaction analysis</a></li><li><a href="https://gaussian.com/vib/" target="_blank" rel="noopener noreferrer">Vibrational analysis</a></li><li><a href="https://psicode.org/psi4manual/master/sapt.html" target="_blank" rel="noopener noreferrer">SAPT documentation</a></li></ul>`,
};

export function expandTheoryBody(body) {
  body = body.replace(/<div class="equation"><math display="block"><mi>ρ<\/mi>[\s\S]*?<\/math><\/div>/, "");
  return body.replace(/<section class="docs-section" id="([^"]+)">([\s\S]*?)<\/section>/g, (section, id, content) =>
    `<section class="docs-section" id="${id}">${content}${additions[id] || ""}</section>`
  );
}
